# Generated by Django 4.0.2 on 2022-04-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar_alter_user_bio_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
