# Generated by Django 4.0.2 on 2022-02-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_body_message_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Description',
            new_name='body',
        ),
    ]
