# Generated by Django 4.0.2 on 2022-02-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_description_message_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-Updated', '-created']},
        ),
    ]
