# Generated by Django 4.0.2 on 2022-02-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-Updated', '-created']},
        ),
    ]
